# Generated by Django 5.1.3 on 2025-02-19 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hospitaluser',
            name='clinical_email',
            field=models.EmailField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='hospitaluser',
            name='clinical_phone',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
