# Generated by Django 5.1.3 on 2025-01-15 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='abstractclinicalemployee',
            managers=[
            ],
        ),
        migrations.AlterModelManagers(
            name='drclinicalemployee',
            managers=[
            ],
        ),
        migrations.AlterModelManagers(
            name='receptionsclinicalemployee',
            managers=[
            ],
        ),
        migrations.RemoveField(
            model_name='abstractclinicalemployee',
            name='username',
        ),
        migrations.AlterField(
            model_name='abstractclinicalemployee',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='drclinicalemployee',
            name='speciality_type',
            field=models.CharField(choices=[('Click to select', 'Click to select'), ('DERMOTOLOGY', 'DERMOTOLOGY'), ('PLASTIC SURGERY', 'PLASTIC SURGERY'), ('Aesthetic Medicine Dermatologist', 'Aesthetic Medicine Dermatologist'), ('SPECIALITY4', 'SPECIALITY4'), ('SPECIALITY5', 'SPECIALITY5'), ('SPECIALITY6', 'SPECIALITY6')], default='Click to select', max_length=50),
        ),
    ]
