# Generated by Django 5.1.3 on 2025-02-19 15:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0002_hospitaluser_clinical_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basiccustomemployee',
            name='username',
            field=models.CharField(null=True),
        ),
        migrations.AlterField(
            model_name='hospitaluser',
            name='head_physician',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hospital_head_physician', to='employees.drclinicalemployee', verbose_name=''),
        ),
    ]
