# Generated by Django 5.1.3 on 2025-02-17 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0002_alter_abstractclinicalemployee_contact_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClinicalCenter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('tax_id', models.CharField(max_length=50)),
                ('clinical_type', models.CharField(choices=[('Clinic', 'Clinic'), ('Hospital', 'Hospital'), ('Laboratory', 'Laboratory'), ('Pharmacy', 'Pharmacy'), ('Diagnostic Center', 'Diagnostic Center'), ('Dental Clinic', 'Dental Clinic')], default='Clinic', max_length=50)),
                ('head_physician', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('country', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=255)),
                ('contact_number', models.CharField(max_length=15)),
                ('zip', models.CharField(max_length=10)),
                ('website', models.URLField()),
                ('slug', models.SlugField(blank=True, max_length=100, unique=True)),
                ('number_of_staff', models.IntegerField(choices=[('1-5', '1-5'), ('6-10', '6-10'), ('11-20', '11-20'), ('21-50', '21-50'), ('51-100', '51-100')], default='1-5')),
                ('number_of_doctors', models.IntegerField(choices=[('1-5', '1-5'), ('6-10', '6-10'), ('11-20', '11-20'), ('21-50', '21-50'), ('51-100', '51-100')], default='6-10')),
            ],
            options={
                'verbose_name': 'Clinical Center',
                'verbose_name_plural': 'Clinical Centers',
            },
        ),
        migrations.AlterField(
            model_name='drclinicalemployee',
            name='speciality_type',
            field=models.CharField(choices=[('Click to select', 'Click to select'), ('DERMOTOLOGY', 'DERMOTOLOGY'), ('PLASTIC SURGERY', 'PLASTIC SURGERY'), ('Aesthetic Medicine Dermatologist', 'Aesthetic Medicine Dermatologist')], default='Click to select', max_length=50),
        ),
    ]
