# Generated by Django 5.1.3 on 2025-01-15 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0002_alter_abstractclinicalemployee_managers_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='abstractclinicalemployee',
            name='contact_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='abstractclinicalemployee',
            name='employee_type',
            field=models.CharField(choices=[('Click to select', 'Click to select'), ('DR', 'Doctor'), ('RECEPTION', 'Reception')], default='Click to select', max_length=50),
        ),
    ]
