# Generated by Django 5.1.3 on 2025-02-19 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=256)),
                ('email', models.EmailField(blank=True, max_length=256)),
                ('tel', models.CharField(blank=True, null=True)),
                ('nif', models.CharField(blank=True, null=True)),
                ('sns', models.CharField(blank=True, null=True)),
                ('address', models.CharField(max_length=256)),
                ('birthday', models.DateField(blank=True, default='1900-01-01', null=True)),
                ('slug', models.SlugField(max_length=256)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Customer',
                'verbose_name_plural': 'Customers',
                'ordering': ['-created'],
            },
        ),
    ]
